import { Cliente, ClienteRepository, EstadoCuenta, validateCliente, CreateClienteResult } from "@/domains/cliente/cliente";

/**
 * Cliente input type for create operations
 * Omits id and fechaAlta (read-only, auto-generated by Prisma)
 */
export interface ClienteInput {
  nombre: string;
  dni: string;
  email: string;
  telefono?: string;
  membresiaAsignada: string;
  estadoCuenta: EstadoCuenta;
}

/**
 * Handle POST /api/clientes
 * Creates a new cliente
 * @returns CreateClienteResult with Cliente + plaintext tempPassword (ephemeral)
 */
export async function handleClienteCreate(data: ClienteInput): Promise<CreateClienteResult> {
  const clienteRepo = new ClienteRepository();
  return clienteRepo.create({
    nombre: data.nombre,
    dni: data.dni,
    email: data.email,
    telefono: data.telefono,
    membresiaAsignada: data.membresiaAsignada,
    estadoCuenta: data.estadoCuenta,
  });
}

/**
 * Handle GET /api/clientes
 * Lists all clientes
 */
export async function handleClienteList(): Promise<Cliente[]> {
  const clienteRepo = new ClienteRepository();
  return clienteRepo.list();
}

/**
 * Handle GET /api/clientes/:id
 * Retrieves a single cliente by ID
 */
export async function handleClienteGet(id: string): Promise<Cliente | null> {
  const clienteRepo = new ClienteRepository();
  return clienteRepo.getById(id);
}

/**
 * Handle PUT /api/clientes/:id
 * Updates a cliente
 * AC-007: id and fechaAlta are read-only (never editable)
 */
export async function handleClienteUpdate(
  id: string,
  data: Partial<ClienteInput>
): Promise<Cliente | null> {
  const clienteRepo = new ClienteRepository();
  return clienteRepo.update(id, data);
}

/**
 * Handle DELETE /api/clientes/:id
 * Deletes a cliente
 */
export async function handleClienteDelete(id: string): Promise<void> {
  const clienteRepo = new ClienteRepository();
  return clienteRepo.delete(id);
}

/**
 * ============================================
 * CLIENT-SIDE API FUNCTIONS (for page.tsx)
 * ============================================
 */

/**
 * Client-side API call: fetch all clientes
 */
export async function fetchClientes(): Promise<Cliente[]> {
  const response = await fetch("/api/clientes");
  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.message || "Failed to fetch clientes");
  }
  return response.json();
}

/**
 * Client-side API call: create a new cliente
 * Adapts API response to standard contract: { cliente, tempPassword }
 * Supports both wrapped format { cliente, tempPassword } and flat format { ...cliente, tempPassword }
 * @returns { cliente, tempPassword } where tempPassword is UNA SOLA VEZ
 */
export async function createCliente(
  data: ClienteInput
): Promise<{ cliente: Cliente; tempPassword: string }> {
  const response = await fetch("/api/clientes", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  });
  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.message || "Failed to create cliente");
  }

  const json = await response.json();

  // B1 fix: Support both wrapped { cliente, tempPassword } and flat { ...cliente, tempPassword }
  if (json.cliente) {
    // Already wrapped format
    return json;
  }

  // Flat format: extract tempPassword and status, rest is cliente data
  const { tempPassword, status, ...clienteData } = json;
  return {
    cliente: clienteData as Cliente,
    tempPassword,
  };
}

/**
 * Client-side API call: update a cliente
 */
export async function updateCliente(
  id: string,
  data: Partial<ClienteInput>
): Promise<Cliente> {
  const response = await fetch(`/api/clientes/${id}`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  });
  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.message || "Failed to update cliente");
  }
  return response.json();
}

/**
 * Client-side API call: delete a cliente
 */
export async function deleteCliente(id: string): Promise<void> {
  const response = await fetch(`/api/clientes/${id}`, {
    method: "DELETE",
  });
  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.message || "Failed to delete cliente");
  }
}
