import { Cliente, ClienteRepository, EstadoCuenta, validateCliente } from "@/domains/cliente/cliente";

/**
 * Cliente input type for create operations
 * Omits id and fechaAlta (read-only, auto-generated by Prisma)
 */
export interface ClienteInput {
  nombre: string;
  dni: string;
  email: string;
  telefono?: string;
  membresiaAsignada: string;
  estadoCuenta: EstadoCuenta;
}

/**
 * Handle POST /api/clientes
 * Creates a new cliente
 */
export async function handleClienteCreate(data: ClienteInput): Promise<Cliente> {
  const clienteRepo = new ClienteRepository();
  return clienteRepo.create({
    nombre: data.nombre,
    dni: data.dni,
    email: data.email,
    telefono: data.telefono,
    membresiaAsignada: data.membresiaAsignada,
    estadoCuenta: data.estadoCuenta,
  });
}

/**
 * Handle GET /api/clientes
 * Lists all clientes
 */
export async function handleClienteList(): Promise<Cliente[]> {
  const clienteRepo = new ClienteRepository();
  return clienteRepo.list();
}

/**
 * Handle GET /api/clientes/:id
 * Retrieves a single cliente by ID
 */
export async function handleClienteGet(id: string): Promise<Cliente | null> {
  const clienteRepo = new ClienteRepository();
  return clienteRepo.getById(id);
}

/**
 * Handle PUT /api/clientes/:id
 * Updates a cliente
 * AC-007: id and fechaAlta are read-only (never editable)
 */
export async function handleClienteUpdate(
  id: string,
  data: Partial<ClienteInput>
): Promise<Cliente | null> {
  const clienteRepo = new ClienteRepository();
  return clienteRepo.update(id, data);
}

/**
 * Handle DELETE /api/clientes/:id
 * Deletes a cliente
 */
export async function handleClienteDelete(id: string): Promise<void> {
  const clienteRepo = new ClienteRepository();
  return clienteRepo.delete(id);
}
