/**
 * Membresia Domain Model
 * Handles creation, validation, and state transitions for memberships
 * AC-001 to AC-007: See openspec/specs/membresias-crud/spec.md
 */

export type EstadoMembresia = "ACTIVA" | "INACTIVA";

export interface Membresia {
  id: string;
  nombre: string;
  precio: number; // Always number — Prisma Decimal is converted to number by mapper
  periodicidad: number; // Days as positive integer
  descripcion?: string | null;
  estado: EstadoMembresia;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Prisma model for Membresia (matches schema)
 * Used internally by repository to type Prisma results
 */
interface PrismaMembresiaRecord {
  id: string;
  nombre: string;
  precio: any; // Prisma Decimal type
  periodicidad: number;
  descripcion: string | null;
  estado: EstadoMembresia;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Map Prisma membresia record to domain Membresia
 * Explicitly converts Decimal precio to number
 * Exported for testing purposes to validate Decimal → number conversion
 */
export function mapPrismaToMembresia(
  prismaRecord: PrismaMembresiaRecord
): Membresia {
  return {
    id: prismaRecord.id,
    nombre: prismaRecord.nombre,
    precio: Number(prismaRecord.precio), // Decimal → number
    periodicidad: prismaRecord.periodicidad,
    descripcion: prismaRecord.descripcion,
    estado: prismaRecord.estado,
    createdAt: prismaRecord.createdAt,
    updatedAt: prismaRecord.updatedAt,
  };
}

export interface ValidationResult {
  valid: boolean;
  errors: string[];
}

/**
 * Validate membresia data
 * AC-001: nombre required, 3–50 chars
 * AC-002: precio required, > 0, up to 2 decimals
 * AC-003: periodicidad required, positive integer
 * AC-004: descripcion optional, max 300 chars
 */
export function validateMembresia(
  data: Partial<Membresia>
): ValidationResult {
  const errors: string[] = [];

  // Validate nombre (AC-001)
  if (!data.nombre || data.nombre.trim() === "") {
    errors.push("El nombre de la membresía es requerido");
  } else if (data.nombre.length < 3) {
    errors.push("El nombre debe tener al menos 3 caracteres");
  } else if (data.nombre.length > 50) {
    errors.push("El nombre no puede exceder 50 caracteres");
  }

  // Validate precio (AC-002)
  if (data.precio === undefined || data.precio === null) {
    errors.push("El precio es requerido");
  } else if (typeof data.precio !== "number") {
    errors.push("El precio debe ser un número");
  } else if (data.precio <= 0) {
    errors.push("Debe ser mayor a 0");
  }

  // Validate periodicidad (AC-003)
  if (
    data.periodicidad === undefined ||
    data.periodicidad === null
  ) {
    errors.push("La periodicidad es requerida");
  } else if (typeof data.periodicidad !== "number") {
    errors.push("La periodicidad debe ser un número");
  } else if (!Number.isInteger(data.periodicidad)) {
    errors.push("La periodicidad debe ser un número entero");
  } else if (data.periodicidad <= 0) {
    errors.push("Debe ser mayor a 0");
  }

  // Validate descripcion (AC-004)
  if (
    data.descripcion &&
    data.descripcion.trim().length > 300
  ) {
    errors.push("La descripción no puede exceder 300 caracteres");
  }

  // Validate estado
  if (!data.estado) {
    errors.push("El estado es requerido");
  } else if (!["ACTIVA", "INACTIVA"].includes(data.estado)) {
    errors.push("El estado debe ser ACTIVA o INACTIVA");
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Create a Membresia with required fields (omitting id and timestamp fields)
 * These fields will be generated by Prisma on insert
 */
export function createMembresia(data: {
  nombre: string;
  precio: number;
  periodicidad: number;
  descripcion?: string;
  estado: EstadoMembresia;
}): Omit<Membresia, "id" | "createdAt" | "updatedAt"> {
  return {
    nombre: data.nombre,
    precio: normalizePrecio(data.precio),
    periodicidad: data.periodicidad,
    descripcion: data.descripcion || null,
    estado: data.estado,
  };
}

/**
 * Normalize precio to 2 decimal places
 * Per AC-002: if more than 2 decimals, round or truncate on save
 */
function normalizePrecio(precio: number): number {
  return Math.round(precio * 100) / 100;
}

/**
 * Membresia Repository for database operations
 * Handles CRUD and state transitions for memberships
 */
export class MembresiaRepository {
  private async getPrisma() {
    const { PrismaClient } = await import("@prisma/client");
    return new PrismaClient();
  }

  /**
   * Create a new membresia
   */
  async create(data: {
    nombre: string;
    precio: number;
    periodicidad: number;
    descripcion?: string;
    estado: EstadoMembresia;
  }): Promise<Membresia> {
    const validation = validateMembresia(data);
    if (!validation.valid) {
      throw new Error(`Validation error: ${validation.errors.join(", ")}`);
    }

    const prisma = await this.getPrisma();
    try {
      const normalized = createMembresia(data);
      const prismaResult = await prisma.membresia.create({
        data: {
          nombre: normalized.nombre,
          precio: normalized.precio,
          periodicidad: normalized.periodicidad,
          descripcion: normalized.descripcion,
          estado: normalized.estado,
        },
      });
      return mapPrismaToMembresia(prismaResult);
    } finally {
      await prisma.$disconnect();
    }
  }

  /**
   * Get membresia by id
   */
  async getById(id: string): Promise<Membresia | null> {
    const prisma = await this.getPrisma();
    try {
      const result = await prisma.membresia.findUnique({
        where: { id },
      });
      return result ? mapPrismaToMembresia(result) : null;
    } finally {
      await prisma.$disconnect();
    }
  }

  /**
   * Get all membresias
   */
  async getAll(): Promise<Membresia[]> {
    const prisma = await this.getPrisma();
    try {
      const results = await prisma.membresia.findMany();
      return results.map(mapPrismaToMembresia);
    } finally {
      await prisma.$disconnect();
    }
  }

  /**
   * Get all ACTIVA membresias (for dropdown in Clientes CRUD, AC-004 from spec)
   */
  async getAllActivas(): Promise<Membresia[]> {
    const prisma = await this.getPrisma();
    try {
      const results = await prisma.membresia.findMany({
        where: { estado: "ACTIVA" },
      });
      return results.map(mapPrismaToMembresia);
    } finally {
      await prisma.$disconnect();
    }
  }

  /**
   * Update membresia
   * AC-005: If changing estado to INACTIVA with assigned members, caller must handle warning
   */
  async update(
    id: string,
    data: Partial<{
      nombre: string;
      precio: number;
      periodicidad: number;
      descripcion: string;
      estado: EstadoMembresia;
    }>
  ): Promise<Membresia> {
    // Validate only the fields being updated
    const validation = validateMembresia(data);
    if (!validation.valid) {
      throw new Error(`Validation error: ${validation.errors.join(", ")}`);
    }

    const prisma = await this.getPrisma();
    try {
      const updateData: any = {};
      if (data.nombre !== undefined) updateData.nombre = data.nombre;
      if (data.precio !== undefined)
        updateData.precio = normalizePrecio(data.precio);
      if (data.periodicidad !== undefined)
        updateData.periodicidad = data.periodicidad;
      if (data.descripcion !== undefined)
        updateData.descripcion = data.descripcion;
      if (data.estado !== undefined) updateData.estado = data.estado;

      const prismaResult = await prisma.membresia.update({
        where: { id },
        data: updateData,
      });
      return mapPrismaToMembresia(prismaResult);
    } finally {
      await prisma.$disconnect();
    }
  }

  /**
   * Delete membresia
   * AC-006: Deletion is blocked if membresía is assigned to any Socio
   * Caller must check assigned count and reject if > 0
   */
  async delete(id: string): Promise<void> {
    const prisma = await this.getPrisma();
    try {
      await prisma.membresia.delete({
        where: { id },
      });
    } finally {
      await prisma.$disconnect();
    }
  }

  /**
   * Get count of socios assigned to this membresia
   * Used for deletion guard and deactivation impact warning (AC-005, AC-006)
   */
  async getAssignedSocioCount(membresiaId: string): Promise<number> {
    const prisma = await this.getPrisma();
    try {
      return await prisma.socio.count({
        where: { membresiaAsignadaId: membresiaId },
      });
    } finally {
      await prisma.$disconnect();
    }
  }
}
